spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: passer
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8081

flickr:
  apiKey: e4b3641bbd94a49d92f58413d13f488f
  apiSecret: 4b1301984cbcebed
  appKey: 72157720889418893-ac0ae41f31e95498
  appSecret: 85b06faa54a8329a
